<b>CONTRATO DE RESPONSIVA Y PRESTACIÓN DE SERVICIOS</b> (el 'Contrato') que celebran, por una parte, <b>MASSIVA CONTABILIDAD INNOVADORA SOCIEDAD CIVIL 'MASSIVA'</b>, (<?php echo $razon_social; ?>, con la forma jurídica de Persona <?php echo ($tipo === "1") ? 'Física' : 'Moral'; ?>, RFC: <?php echo $rfc; ?>), y conjuntamente, las 'Partes' e indistintamente una 'Parte', al tenor de las siguientes declaraciones:<br>
<h1>DECLARACIONES</h1>
<h2>1. Declara MASSIVA que:</h2>
<ol type="a">
    <li>Es una sociedad debidamente constituida de conformidad con las leyes de los Estados Unidos Mexicanos como consta en escritura número 100,990 otorgada ante la fe del licenciado, Notario, Lic. Alfredo Ayala Herrera, Titular de la Notaria 237, de la Ciudad de México, el día 7 de febrero de 2019, acreditando a su vez a su representante con las facultades suficientes para celebrar este Contrato.</li>
    <li>Se encuentra inscrita en el Registro Federal de Contribuyentes bajo el número <strong>MCI1902072A6.</strong></li>
</ol>
<h2>2. Declara el Cliente que:</h2>
<ol type="a">
    <li>Es una Persona Física o Moral debidamente constituida de conformidad con las leyes de la República Mexicana, contando su representante con las facultades suficientes para celebrar este Contrato, y en caso de ser la primera que cuenta con capacidad legal de acuerdo a lo establecido en el Código Civil vigente. </li>
    <li>Se encuentra adscrito en el Registro Federal de Contribuyentes con número y domicilio fiscal que adjuntan en la plataforma <strong>massiva.mx</strong></li>
    <li>Requiere que <strong>MASSIVA</strong> le preste los servicios como proveedor de facturación electrónica y contabilidad integral digital.</li>
    <li>En virtud de las declaraciones anteriores, las Partes convienen sujetarse a lo dispuesto en las siguientes cláusulas.</li>
</ol>
<h1>CLÁUSULAS</h1>
<h2>1. Objeto.</h2>
<p>Hasta el primer cobro del plan seleccionado implicará la aceptación por parte del cliente a <strong>MASSIVA</strong> de este Contrato, e iniciará la prestación al cliente a través del Sistema, de los servicios de generación y emisión electrónica de CFDIs, recopilación, procesamiento, almacenamiento, manejo y envío de información relativa a las transacciones de CFDIs realizadas para el cliente, además de las declaraciones, cotizaciones, facturación de tickets (comprobante fiscal), sincronización de cuentas bancarias, nóminas y pago de impuestos a través del Sitio Web, los cuales se describen a mayor detalle en el Anexo &quot;A&quot;  &ldquo;B&rdquo; y &ldquo;C&rdquo; del presente contrato (&quot;de Servicios&quot;)</p>
<h2>2. Precios.</h2>
<ol type="a">
    <li>&ldquo;El Cliente&rdquo; pagará a <strong>MASSIVA</strong>, como contraprestación, las cantidades estipuladas en el referido Anexo &quot;A&quot; de este Contrato (&quot;la Contraprestación&quot;), incluido el Impuesto al Valor Agregado (I.V.A.) correspondiente.</li>
    <li>&ldquo;El Cliente&rdquo; pagará a <strong>MASSIVA</strong> a través del sistema <strong>OPENPAY</strong>, que analiza cada transacción en tiempo real con el <strong>sistema antifraude</strong>, información <strong>encriptada con certificados SSL y bajo la certificación PCI-DSS</strong> para el manejo y almacenamiento de tarjetas, las cantidades estipuladas en el referido Anexo &ldquo;B&rdquo; de este Contrato (&quot;la Contraprestación&quot;), incluido el Impuesto al Valor Agregado (I.V.A.) correspondiente.</li>
    <li>&ldquo;El Cliente&rdquo; pagará a <strong>MASSIVA</strong> por penalización y costos adicionales por uso extraordinario, las cantidades estipuladas en el referido Anexo &ldquo;C&rdquo; de este Contrato (&quot;la Contraprestación&quot;), incluido el Impuesto al Valor Agregado (I.V.A.) correspondiente.</li>
</ol>
<h2>3. Forma de Pago.</h2>
<ol type="a">
    <li>La contraprestación por el Servicio será exigible y pagadera por el Cliente conforme a lo siguiente:</li>
    <li>I.- &quot;El Cliente&quot; al momento de registrarse en la plataforma y aceptar las condiciones de llevar su contabilidad integral digital, lo cual incluye realización de facturas a su nombre, con previa solicitud de &ldquo;El Cliente&rdquo;, realización de declaraciones, sincronización de cuentas bancarias, nóminas, si se solicita, cotizaciones, aviso y pago de impuestos, si corresponde, respetando los costos señalados en el Anexo A de este Contrato. Posterior al pago realizado por &quot;El Cliente&quot; y a la entrega de todos los archivos y datos necesarios para poder emitir una factura electrónica y llevar su contabilidad integral digital, <strong>MASSIVA</strong> habilitará en un plazo no mayor a 48 horas, el sistema para la solicitud y generación de CFDI con sus folios correspondientes según su plan contratado.</li>
    <li>El pago del plan mensual contratado en el Anexo &ldquo;A&rdquo; solicitado por el &quot;El Cliente&quot; podrá ser mediante depósito bancario o transferencia bancaria con las tarjetas de VISA, MASTERCARD y AMERICAN EXPRESS al Banco <strong>BANREGIO</strong>, número de cuenta <strong>220 93562 001 5</strong>, CLABE <strong>058180000002766829</strong> de <strong>MASSIVA.</strong></li>
    <li>En caso de que el Cliente no realice el pago convenido de la Contraprestación a favor de <strong>MASSIVA</strong> conforme a este Contrato, <strong>MASSIVA </strong>tendrá el derecho de suspender la prestación del Servicio sin previo aviso y de forma inmediata.</li>
</ol>
<h2>4. Límites de Responsabilidad</h2>
<p>&quot;El Cliente&quot; se obliga a cumplir con las obligaciones fiscales adquiridas por la contratación las cuales son:</p>
<ol type="a">
    <li>Autorizar la entrega al Servicio de Administración Tributaria (SAT), copia de los comprobantes fiscales que hayan realizado con <strong>MASSIVA</strong>, de acuerdo a lo establecido en la regla <strong>2.7.4.1 – 2.21.2 </strong>de conformidad con la  miscelánea fiscal para el 2018  y en complemento ANEXO 24 de la miscelánea fiscal del 2015 (<a href="https://www.gob.mx/sat/acciones-y-programas/articulo-28-del-codigo-fiscal-de-la-federacion-144607?state=published">Artículo 28</a> del Código Fiscal de la Federación, <a href="https://www.gob.mx/sat/acciones-y-programas/articulos-33-y-34?state=published">Artículos 33 y 34</a> del Reglamento del Código Fiscal de la Federación, <a href="http://pi.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/extracto_reglas.pdf" target="_blank">Extracto de las Reglas de Contabilidad electrónica</a> de la Resolución&nbsp;Miscelánea Fiscal para 201<a href="http://www.sat.gob.mx/informacion_fiscal/normatividad/Documents/1_RMF2015_03032015.doc" target="_blank">8</a>&nbsp;(Extracto de la publicada en el <em>Diario Oficial de la Federación</em><em>&nbsp;e</em>l&nbsp;03 de marzo 2015), <a href="http://pi.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/Anexo24_05012015.pdf" target="_blank">Anexo 24​</a> de la&nbsp;Resolución&nbsp;de modificaciones&nbsp;a la Resolución Miscelánea Fiscal 201<a href="http://pi.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/2_RMF2015_contabilidad.pdf" target="_blank">8</a> (Extracto de la publicada en el <em>Diario Oficial de la Federación</em> el 14 de mayo de 2015)<a href="http://pi.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/3_RMF2015_contabilidad.pdf" target="_blank">Tercera Resolución de Modificaciones a la Resolución Miscelánea Fiscal 2015</a>(Extracto de la publicada en el <em>Diario Oficial de la Federació</em><em>n</em> el&nbsp;02 de&nbsp;julio de 2015). </li>
    <li>Conservar en medios electrónicos actualizados las Facturas Electrónicas y tenerlas a disposición de las autoridades fiscales.</li>
    <li>Conservar dentro de la plataforma <strong>massiva.mx</strong>, en el perfil del Cliente, de forma limitada, su documentación e información hasta que decida darse de baja de forma voluntaria o hasta que <strong>MASSIVA</strong> dé de baja al Cliente por falta de pago. Dicha información quedará hospedada en la plataforma de <strong>massiva.mx</strong> únicamente por 15 (quince) días, pasado ese límite de tiempo toda información quedará eliminada dentro de la plataforma <strong>massiva.mx</strong>.</li>
</ol>
<p>&ldquo;El Cliente&rdquo; deberá descargar toda su información de su perfil antes de darse de baja, si lo hace después, deberá solicitarla a <a href="mailto:atencionclientes@massiva.mx">atencionclientes@massiva.mx</a> y antes de los 15 días de haberlo hecho porque su información será eliminada del sistema de <strong>MASSIVA</strong> a partir del día 16 desde que se dio de baja.</p>
<h2>5. Obligatoriedad de resguardo de toda la documentación</h2>
<p>&ldquo;El Cliente&rdquo; está obligado de hacer resguardo de su propia información durante al menos 5 años.<br>
    <strong>MASSIVA</strong> resguardará toda su documentación e información mientras sea cliente de <strong>MASSIVA</strong> y el Cliente podrá hacer un corte de su contabilidad en una sección de su Perfil llamada Respaldo, la cual podrá enviarse a su correo si así lo desea.</p>
<h2>6. Autorización declaraciones</h2>
<p>&ldquo;El Cliente&rdquo; tiene la obligación de autorizar la declaración mensual de su contabilidad a través de la plataforma presionando el botón &ldquo;Autorizar&rdquo; o bien, si no desea en ese momento autorizar, puede presionar los botones de &ldquo;esperar&rdquo; y &ldquo;esperar más&rdquo;. Una vez que &ldquo;El Cliente&rdquo; presione el botón &ldquo;Autorizar&rdquo;, se le está dando la autorización a <strong>MASSIVA</strong> de sincronizar y realizar los cálculos correspondientes basados en la información (facturas) proporcionada por &ldquo;El Cliente&rdquo; y descargada directamente desde el Portal del SAT del cliente que estará ubicada en su perfil, además de la conciliación con sus estados de cuenta o movimientos bancarios.</p>
<h2>7. Pago de impuestos</h2>
<p>&ldquo;El Cliente&rdquo; tiene la obligación de pagar los impuestos a través de su banca digital o en ventanilla. <strong>MASSIVA</strong> únicamente le avisará cuando deba hacerlo y le proporcionará al cliente el acuse a través de la plataforma para el pago en tiempo y forma. Si el cliente se retrasara en la descarga y pago de sus impuestos, es responsabilidad únicamente del cliente, el cual debe dar aviso a <strong>MASSIVA</strong> para volver a obtener un nuevo acuse con los recargos o multas si los hubiera por dicho retraso.</p>
<h2>8. Uso del Sistema. </h2>
<ol type="a">
    <li>&ldquo;El Cliente&rdquo; reconoce y acepta que los servicios contenidos en el presente contrato se prestan a través del Sistema, cuyo uso se pone a disposición del Cliente en el Sitio Web bajo el URL <strong>www.massiva.mx,</strong> el cual cumple con todos los requisitos señalados en las disposiciones fiscales para emitir comprobantes fiscales digitales.</li>
    <li>&ldquo;Las Partes&rdquo; convienen que para todo lo relacionado con la operación del Sistema, <strong>MASSIVA</strong> proporcionará al Cliente las reglas vigentes que estarán en el manual que para ese efecto mantenga publicado dentro del Sitio Web.</li>
    <li><strong>MASSIVA</strong> podrá modificar dichos <strong>Términos y Condiciones</strong> de uso del Sistema y el Sitio Web cuando lo crea conveniente, buscando no afectar al Cliente en sus procedimientos de trabajo, o bien cuando así lo marque la ley. Dichos cambios podrán realizarse sin previo aviso al Cliente, cambios que incluyen en forma ejemplificativa más no limitativa, cambios y mejoras al Sistema, cambio de diseños y colores, organización de funciones, agregar nuevos servicios, cambios a los procedimientos de emisión y/o cancelación de CFDIs u otras operaciones.</li>
</ol>
<h2>9. Conservación de Base de Datos ante Caso Fortuito o de Fuerza Mayor.</h2>
<p>En caso de que <strong>MASSIVA</strong> no pueda prestar los servicios contenidos en el servicio por más de 15 (quince) días naturales consecutivos con motivo de casos fortuitos, fuerza mayor o en general por causas no atribuibles a la misma, <strong>MASSIVA </strong>tan pronto sea posible devolverá al Cliente su Base de Datos, salvo que el Cliente decida que <strong>MASSIVA</strong> continúe conservándola. &ldquo;El Cliente&rdquo; tendrá 30 (treinta) días naturales a partir del siguiente día al que se haya suspendido el servicio, para solicitar la devolución de su Base de Datos a <strong>MASSIVA</strong>. Transcurrido dicho plazo, se entenderá que el Cliente ha solicitado a <strong>MASSIVA</strong> que conserve dicha Base de Datos hasta nuevo aviso.</p>
<h2>10. Vigencia y Terminación.</h2>
<ol type="a">
    <li>El presente Contrato se celebra por tiempo indefinido una vez aceptado.</li>
    <li>En caso de rescisión de este Contrato, &ldquo;El Cliente&rdquo; deberá haber pagado a <strong>MASSIVA</strong> la Contraprestación generada hasta esa fecha y cumplido con las demás obligaciones a su cargo bajo este Contrato.</li>
    <li>No obstante lo anterior, cualquiera de las partes podrá rescindir de pleno derecho este Contrato, sin necesidad de declaración judicial, mediante simple aviso vía correo electrónico 5 (cinco) días naturales antes de la fecha de corte dirigido a la otra Parte, en caso de que la otra Parte incumpla con cualquiera de sus obligaciones establecidas en este Contrato o en los términos y condiciones de uso del Sitio Web. En este caso la Parte Incumplida tendrá un plazo de 15 (quince) días naturales siguientes al aviso de la Parte afectada para subsanar su incumplimiento. Una vez transcurrido dicho plazo sin que la Parte incumplida hubiere remediado su incumplimiento a satisfacción de <strong>MASSIVA</strong>, la rescisión de este contrato operará de forma automática.</li>
</ol>
<h2>11. Avisos.</h2>
<ol type="a">
    <li>En caso de rescisión del presente contrato por parte de &quot;El Cliente&quot;, no será reembolsable cantidad alguna pagada anticipadamente a <strong>MASSIVA</strong> por ningún concepto.</li>
    <li>Cualquier aviso, requerimiento, notificación y demás comunicaciones relativas a este Contrato deberá ser por vía correo electrónico.</li>
</ol>
<p>Dichas comunicaciones surtirán sus efectos en la fecha en que hayan sido registradas por los servidores de correo electrónico de <strong>MASSIVA</strong> y/o del Cliente.<br>
    Las comunicaciones vía correo electrónico deberán enviarse a la siguiente dirección de correo electrónico:<br>
    Si es dirigida a <strong>MASSIVA</strong>, a: <a href="mailto:atencionclientes@massiva.mx">atencionclientes@massiva.mx</a> <br>
    Si es dirigida al Cliente, a: Se enviará a la dirección registrada en el portal <a href="http://www.faccil.mx">massiva.mx</a></p>
<h2>12. Acuerdo Único y Modificaciones.</h2>
<ol type="a">
    <li>Este Contrato y sus anexos contienen la totalidad del acuerdo entre las Partes formando en conjunto un solo instrumento, razón por la cual las Partes dejan sin efecto legal cualquier otro acuerdo legal o escrito que hayan acordado o suscrito con fecha anterior a la fecha de celebración del mismo.</li>
    <li>Este contrato sólo podrá ser modificado mediante convenio escrito firmado por las Partes.</li>
</ol>
<h2>13. Ley Aplicable y Jurisdicción.</h2>
<p><strong>MASSIVA</strong> y &ldquo;El Cliente&rdquo; convienen que para todo lo relacionado con este Contrato se sujetan expresamente a las leyes vigentes y tribunales competentes en Ciudad de México, México, renunciando a cualquier otra jurisdicción que les pudiera corresponder ahora o en el futuro en razón de sus domicilios o por cualquier otra causa.</p>